# title: Sickada
# description: Sickada
baseurl: "" # Leave this empty unless your site is in a subfolder

# Theme Configuration (Optional)
theme: minima # Disables default themes like Minima
markdown: kramdown # Default Markdown processor for GitHub Pages

# Exclude Jekyll default sidebar and other unwanted files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Default Layouts for Markdown Files
defaults:
  - scope:
      path: "" # Applies to all files
      type: "pages"
    values:
      layout: no-sidebar # Use a custom layout without a sidebar

show_sidebar: false
